echo "Demo: Using the improved rating system"
echo "====================================="
echo "Option 5 now has two methods:"
echo "  1. Enter ObjectId directly (24 characters)"
echo "  2. Search for restaurant by name/cuisine, then rate"
echo ""
echo "Example ObjectIds you can try:"
echo "  McDonald's: 5eb3d668b31de5d588f429f9"
echo ""
echo "Or just search for: McDonald, Subway, Pizza, etc."
